(()=>{
'use strict';
const $=s=>document.querySelector(s),input=$('#fileInput'),drop=$('#dropzone'),editor=$('#editor'),target=$('#targetSize'),range=$('#sizeRange'),format=$('#format'),compress=$('#compressBtn'),progress=$('#progress'),result=$('#result'),download=$('#downloadBtn');
const allowed=new Set(['image/jpeg','image/png','image/webp','image/avif']);
let file=null,previewUrl=null,outputUrl=null,outputBlob=null,maxSizeKB=30000,busy=false;
$('#year').textContent=new Date().getFullYear();
const bytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(0)} KB`:`${(n/1048576).toFixed(2)} MB`;
function clearOutput(){result.classList.add('hidden');$('#resultPreview').removeAttribute('src');download.removeAttribute('href');$('#openImageBtn').removeAttribute('href');if(outputUrl)URL.revokeObjectURL(outputUrl);outputUrl=null;outputBlob=null;}
function reset(){if(busy)return;file=null;clearOutput();if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=null;$('#fileThumb').style.backgroundImage='none';editor.classList.add('hidden');drop.classList.remove('hidden');drop.focus();}
function loadFile(f){if(busy||!f)return;if(!allowed.has(f.type))return alert('Choose a JPG, PNG, WebP or AVIF image.');if(f.size>100*1024*1024)return alert('This file is over 100 MB. Please choose a smaller image.');if(!f.size)return alert('This file is empty. Please choose another image.');file=f;clearOutput();$('#fileName').textContent=f.name;$('#fileMeta').textContent=`${bytes(f.size)} · ${f.type.split('/')[1].toUpperCase()}`;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(f);$('#fileThumb').style.backgroundImage=`url("${previewUrl}")`;maxSizeKB=Math.max(10,Math.min(30000,Math.floor(f.size/1024)));range.max=String(maxSizeKB);target.value=String(Math.max(10,Math.min(maxSizeKB,Math.round(f.size/1024*.55))));range.value=target.value;drop.classList.add('hidden');editor.classList.remove('hidden');target.focus();}
function decode(f){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(f);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('This image could not be opened by your browser. Try a JPG, PNG or WebP image.'))};img.src=url;});}
function encode(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>{if(!blob)return reject(Error('Your browser could not encode this image. Try a smaller image.'));if(blob.type!==type)return reject(Error('Your browser does not support this output format. Please try JPEG.'));resolve(blob)},type,quality));}
function setBusy(value){busy=value;for(const el of [input,target,range,format,compress,$('#removeBtn'),$('#newImageBtn')])el.disabled=value;progress.classList.toggle('hidden',!value);editor.setAttribute('aria-busy',String(value));}
async function compressImage(){if(!file||busy)return;const maxKB=Number(target.value);if(!Number.isFinite(maxKB)||maxKB<10||maxKB>30000){alert('Enter a target size between 10 and 30,000 KB.');target.focus();return;}const current=file,type=format.value,goal=maxKB*1024;setBusy(true);clearOutput();let canvas;try{const img=await decode(current);canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d',{alpha:type==='image/webp'});if(!ctx||!canvas.width||!canvas.height)throw Error('This image is too large for your browser. Try a smaller image.');if(type==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.drawImage(img,0,0);let lo=.15,hi=.95;const smallest=await encode(canvas,type,lo);let out=smallest;if(smallest.size<=goal){const highest=await encode(canvas,type,hi);if(highest.size<=goal)out=highest;else{for(let i=0;i<8;i++){const q=(lo+hi)/2,b=await encode(canvas,type,q);if(b.size<=goal){out=b;lo=q}else hi=q;}}}outputBlob=out;outputUrl=URL.createObjectURL(out);download.href=outputUrl;download.download=`${current.name.replace(/\.[^.]+$/,'')}-compressed.${type==='image/webp'?'webp':'jpg'}`;$('#openImageBtn').href=outputUrl;$('#resultPreview').src=outputUrl;$('#originalSize').textContent=bytes(current.size);$('#compressedSize').textContent=bytes(out.size);const pct=Math.max(0,Math.round((1-out.size/current.size)*100));$('#savedLabel').textContent=out.size<current.size?`${pct}% smaller`:'';$('#resultNote').textContent=out.size>goal?`The smallest result at the supported quality is ${bytes(out.size)}. The ${maxKB} KB target could not be reached while keeping the original dimensions.`:out.size>=current.size?'The converted file is not smaller than the original. Try WebP or a lower target size.':'Dimensions kept. Review the preview before using your image.';result.classList.remove('hidden');result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}catch(e){clearOutput();alert(e.message||'Compression failed. Please try another image.');}finally{if(canvas){canvas.width=0;canvas.height=0;}setBusy(false);}}
drop.addEventListener('click',e=>{if(e.target!==input)input.click();});
drop.addEventListener('keydown',e=>{if(e.target===drop&&(e.key==='Enter'||e.key===' ')){e.preventDefault();input.click();}});
input.addEventListener('change',()=>{loadFile(input.files[0]);input.value='';});
for(const ev of ['dragenter','dragover'])drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragover');});
for(const ev of ['dragleave','drop'])drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragover');});
drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
range.addEventListener('input',()=>{target.value=range.value;clearOutput();});
target.addEventListener('input',()=>{if(Number(target.value)>=10)range.value=String(Math.min(maxSizeKB,Number(target.value)));clearOutput();});
format.addEventListener('change',clearOutput);
download.addEventListener('click',e=>{if(!outputBlob){e.preventDefault();return;}if(/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)&&navigator.canShare&&navigator.share){const image=new File([outputBlob],download.download,{type:outputBlob.type});if(navigator.canShare({files:[image]})){e.preventDefault();navigator.share({files:[image],title:'Compressed image'}).catch(error=>{if(error.name!=='AbortError')alert('Sharing was unavailable. Use “open the image” below to save it.');});}}});
compress.addEventListener('click',compressImage);$('#removeBtn').addEventListener('click',reset);$('#newImageBtn').addEventListener('click',()=>{if(!busy)input.click();});
})();
